### ISSUE TITLE
two identity servers ( Id3 and Saml ) and 7 Internet web apps 

### ISSUE THREAD

**Issue by saurabh12231978** [brockallen/IdentityServerAndApi#1]
hello Allen,

hope you should be in good spirit; with dual support of mind set i put you question that the Id3 server is well federating our openId based apps(with ext logins); the challenge is second setup has Saml. right; you got it, does Id3 support dual federation in single context(Principal); or you want to withdraw your thought ? 
I also welcome your second thought. putting efforts heavily on adding WIF4.5 support to Kentor AuthService then to ID3.
-SS

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
