### ISSUE TITLE
Unable to perform any action on opening web page

### ISSUE THREAD

**Issue by eJamesLee** [brockallen/IdentityServerAndApi#2]
Hi Brock,
I found this resource from: http://docs.identityserver.io and was exploring your solution.
In an exercise to follow through the Login process, I went into debug mode with a few breakpoints.  However after navigating to the opening page, I am unable to perform any actions.

I have included a screenshot of what I see.  Hope I am not missing something basic here.

Thank you in advance.
- James

![Opening_Page](https://user-images.githubusercontent.com/48037189/57009696-06da6100-6bad-11e9-8f05-f8d43c7cb54c.png)

**Comment by brockallen** [comment]
I bet it's a CORS issue.

**Comment by danlavrushko** [comment]
@eJamesLee as I see from screenshot, your application runs at port 51085, but should at 5000.

**Comment by brockallen** [comment]
So then change the host to run on 5000.

**Comment by eJamesLee** [comment]
Dan and Brock

I updated the launchSettings.json file under Properties from 51085 and 51086 (respectively) to 5000 and 5000 (not 5001).  Both ports should be 5000 from what I can see in the app - please correct me if needed.

After updating these ports, I was immediately able to see functionality on the page.  Thank you for catching this!

So you have it, here is the complete launchSettings.json file below:

{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:5000/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IdentityServerHost": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:5000/"
    }
  }
}
